import { MedFormFieldConfig, FIELD_TYPES, PATTERN_TYPES } from "med-dynamic-form";

export const FORM_CONFIG: MedFormFieldConfig[] = [
  {
    key: 'cpv_code',
    label: 'CPV-код',
    editorType: FIELD_TYPES.SELECT,
    class: 'field col-12 md:col-6',
    required: true,
    onSelect: (t: string) => console.log('select: ', t)
  },
  {
    key: 'checkbox',
    label: 'checkbox',
    editorType: FIELD_TYPES.CHECKBOX,
    class: 'field col-12 md:col-6',
  },
  {
    key: 'email',
    label: 'E-mail',
    editorType: FIELD_TYPES.TEXT,
    placeholder: 'ex@gmail.com',
    required: true,
    class: 'field col-12 md:col-6',
  },
  {
    key: 'responsible',
    label: 'Відповідальний менеджер',
    editorType: FIELD_TYPES.SELECT,
    class: 'field col-12 md:col-6',
  },
  {
    key: 's20',
    label: 'Доведена кількість МОЗ',
    editorType: FIELD_TYPES.NUMBER,
    class: 'field col-12 md:col-6',
    required: true,
  },
  {
    key: 'publisher',
    label: 'Відповідальна особа за підписання',
    editorType: FIELD_TYPES.SELECT,
    class: 'field col-12 md:col-6',
  },
  {
    key: 'autocomplete',
    label: 'autocomplete',
    editorType: FIELD_TYPES.AUTOCOMPLETE,
    class: 'field col-12 md:col-6',
    onSelect: (t: string) => console.log('autocomplete: ', t)
  },
  {
    key: 'text',
    label: 'TEXT',
    editorType: FIELD_TYPES.TEXT,
    class: 'field col-12 md:col-6',
  },
  {
    key: 'DECIMAL',
    label: 'PATTERN_TYPES.DECIMAL',
    editorType: FIELD_TYPES.TEXT,
    pattern: PATTERN_TYPES.DECIMAL,
    class: 'field col-12 md:col-6',
  },
  {
    key: 'LATIN_AND_NUMBER',
    label: 'PATTERN_TYPES.LATIN_AND_NUMBER',
    editorType: FIELD_TYPES.TEXT,
    pattern: PATTERN_TYPES.LATIN_AND_NUMBER,
    class: 'field col-12 md:col-6',
  },
  {
    key: 'agreement_fact_date',
    label: 'Дата підписання договору',
    editorType: FIELD_TYPES.DATE,
    class: 'field col-12 md:col-6',
  },
  {
    key: 'api_id',
    label: 'API Prozorro',
    editorType: FIELD_TYPES.TEXT,
    class: 'field col-12 md:col-6',
  },
];

export const DATALIST: string[] = [
  "Гетеро Лабз Лімітед",
  "ГЕТЕРО ЛАБЗ ЛІМІТЕД",
  "Гетеро Лабз Лімітед",
  "Еббві Дойчленд ГмбХ і Ко.",
  "Еббві Дойчленд ГмбХ і Ко. КГ",
  "Мерк Шарп і Доум Б.В., Нідерланди; МСД Інтернешнл ГмбХ (філія Сінгапур), Сінгапур; МСД Інтернешнл ГмбХ / МСД Ірландія (Беллідайн), Ірландія",
  "Еббві Дойчленд ГмбХ і Ко. КГ",
  "Гетеро Лабз Лімітед",
  "Майлан Лабораторіз Лімітед",
  "Майлан Лабораторіз Лімітед",
  "А/Т Ново Нордіск",
  "А/Т Ново Нордіск",
  "А/Т Ново Нордіск",
  "А/Т Ново Нордіск",
  "Октафарма АБ, Октафарма Фармацевтика Продуктіонсгес м.б.Х., Октафарма",
  "КЕДРІОН С.П.А., ",
  "КЕДРІОН С.П.А",
  "КЕДРІОН С.П.А.",
  "А/Т Ново Нордіск",
  "А/Т Ново Нордіск",
  "Ф.Хоффманн-Ля Рош Лтд",
  "Ф.Хоффманн-Ля Рош Лтд",
  "Ф.Хоффманн-Ля Рош Лтд",
  "Феррінг ГмбХ",
  "Фармацiя i Апджон Компанi,",
  "ТОВ \"ФАРМЕКС Груп\"",
  "Гетеро Лабз Лімітед",
  "Пфайзер Менюфекчуринг Бельгія НВ",
  "Актавіс, С.п.А.",
  "Ф. Хоффманн-Ля Рош Лтд (первинне та вторинне пакування, випробування контролю якості, випуск серії), Швейцарія Кетелент Джермані Ебербах ГмбХ (виробництво нерозфасованої продукції, випробування контролю якості), Німеччина",
  "Ф. Хоффманн-Ля Рош Лтд (первинне та вторинне пакування, випробування контролю якості, випуск серії), Швейцарія Кетелент Джермані Ебербах ГмбХ (виробництво нерозфасованої продукції, випробування контролю якості), Німеччина",
  "Гетеро Лабз Лімітед",
  "Гетеро Лабз Лімітед",
  "АЦС ДОБФАР С.П.А."
]
