import { FILTER_TYPES, MedTableColumnConfig, FIELD_TYPES, PATTERN_TYPES } from 'med-table';

export const TABLE_CONFIG: MedTableColumnConfig[] = [
  {
    key: 'cpv_code',
    label: 'CPV-код',
    filterable: true,
    editorType: FIELD_TYPES.SELECT,
    minWidth: '10rem',
  },
  {
    key: 'responsible',
    sortKey: 'responsible.name',
    label: 'Відповідальний менеджер',
    filterable: true,
    editorType: FIELD_TYPES.SELECT,
    viewHandler: ({name}: any) => name || '–',
  },
  {
    key: 's20',
    label: 'Доведена кількість МОЗ',
    filterable: true,
    editorType: FIELD_TYPES.NUMBER,
    defaultValue: '0',
  },
  {
    key: 'tender_quantity',
    label: 'Кількість закупівлі',
    filterable: true,
    editorType: FIELD_TYPES.NUMBER,
    defaultValue: '0',
  },
  {
    key: 'publisher',
    sortKey: 'publisher.name',
    label: 'Відповідальна особа за підписання',
    filterable: true,
    editorType: FIELD_TYPES.SELECT,
    viewHandler: ({name}: any) => name || '–',
    filterType: FILTER_TYPES.SELECT,
  },
  {
    key: 'agreement_value',
    label: 'Сума позиції за договором',
    filterable: true,
    editorType: FIELD_TYPES.TEXT,
    pattern: PATTERN_TYPES.DECIMAL,
  },
  {
    key: 'agreement_num',
    label: 'Номер договору',
    filterable: true,
    editorType: FIELD_TYPES.TEXT,
  },
  {
    key: 'agreement_fact_date',
    label: 'Дата підписання договору',
    filterable: true,
    editorType: FIELD_TYPES.DATE,
    filterType: FILTER_TYPES.DATE,
  },
  {
    key: 'agreement_final_date',
    label: 'Кінцева дата дії договору',
    filterable: true,
    editorType: FIELD_TYPES.DATE,
    filterType: FILTER_TYPES.DATE,
  },
  {
    key: 'delivery_date',
    label: 'Строк поставки',
    filterable: true,
    editorType: FIELD_TYPES.DATE,
    filterType: FILTER_TYPES.DATE,
  },
  {
    key: 'winner',
    label: 'Переможець',
    filterable: true,
    editorType: FIELD_TYPES.TEXT,
  },
  {
    key: 'winner_edrpou',
    label: 'ЄДРПОУ переможця',
    filterable: true,
    editorType: FIELD_TYPES.TEXT,
  },
  {
    key: 'manufacturer',
    label: 'Виробник',
    filterable: true,
    editorType: FIELD_TYPES.TEXT,
  },
  {
    key: 'manufacturer_country',
    label: 'Країна виробника',
    filterable: true,
    editorType: FIELD_TYPES.TEXT,
  },
  {
    key: 'trade_name',
    label: 'Торгова назва',
    filterable: true,
    editorType: FIELD_TYPES.TEXT,
  },
  {
    key: 'tender_id',
    label: 'Посилання на Prozorro',
    filterable: true,
    editorType: FIELD_TYPES.TEXT,
  },
  {
    key: 'api_id',
    label: 'API Prozorro',
    filterable: true,
    editorType: FIELD_TYPES.TEXT,
  },
  {
    key: 'quantity',
    label: 'Кількість закупівлі (Додаткова угода)',
    filterable: true,
    editorType: FIELD_TYPES.NUMBER,
  },
  {
    key: 'proc_sum',
    label: 'Сума позиції (Додаткова угода)',
    filterable: true,
    editorType: FIELD_TYPES.TEXT,
    pattern: PATTERN_TYPES.LATIN_AND_NUMBER,
  },
  {
    key: 'agreement_final_date',
    label: 'Кінцева дата дії договору (Додаткова угода)',
    filterable: true,
  },
];
